### ISSUE TITLE
Default prior for `tau_*` leads to NaN estimates

### ISSUE THREAD

**Issue by johaupt** [socket778/XBCF#3]
The default option for the parameters `tau_pr` and `tau_trt` leads to `NaN` estimates and is not well documented. 

1. The default seems to be different than described in Hahn et al 2020 and different from the `bcf` R package. These seem to calculate the default prior `tau_pr` and `tau_trt` as `0.6*var(y)/n_trees_pr` and  `0.1*var(y)/n_trees_trt`, respectively. Why these formulae was not clear to me from the paper or from Chipman et al (2010). 

2. When not specifying `tau_pr` or `tau_trt` in `model.fit()` the estimates for `a[1:]`, `b[1:]` and `tauhats` output are `NaN`. The attached example shows this on the example with generated data from the library folder.
[xbcf_tau_prior_issue_report.pdf](https://github.com/socket778/XBCF/files/6178484/xbcf_tau_prior_issue_report.pdf)

**Comment by socket778** [comment]
The `NaN` issue should not occur anymore -- the defaults for all parameters were just updated with version 0.1.3 of the package (available on PyPI now). At this point the fit function can be run with just data (x, x1, y, z) and two model parameters (`p_categorical_pr` and `p_categorical_trt`) specified.

As for the priors on `tau_pr `and `tau_trt`, it is correct that they are not exactly matching the values for BCF model (however BCF model specifies these priors in a different way in general). Prior parameter specification will be available in XBCF paper which is under revision now. 

Here is the general idea behind these priors: we want to try to distribute the observed outcome variance over three possible sources: the prognostic term, the treatment term and noise. We choose `0.6*var(y)/n_trees_pr` and `0.1*var(y)/n_trees_trt` because it seems reasonable to attribute 60% of the variance to the prognostic term, 10% of variance to the treatment term and the remaining 30%  to noise. If there are some insights on how the variance should be distributed, the user is free to adjust these priors as they'd like.

**Comment by johaupt** [comment]
Can confirm that it worked, thank you!
